version: '3'

services:
  # Configuration for Hub+Proxy
  jupyterhub:
    build: jupyterhub                # Build the container from this folder.
    container_name: jupyterhub_hub   # The service will use this container name.
    volumes: # Give access to Docker socket.
      - /var/run/docker.sock:/var/run/docker.sock
    environment: # Env variables passed to the Hub process.
      DOCKER_JUPYTER_IMAGE: jupyter/scipy-notebook
      DOCKER_NETWORK_NAME: ${COMPOSE_PROJECT_NAME}_default
      HUB_IP: jupyterhub_hub
      HOST: ${HOST}
    labels: # Traefik configuration.
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${HOST}"
    restart: on-failure

  # Configuration for reverse proxy
  reverse-proxy:
    image: traefik:1.7
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./reverse-proxy/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./etc/certs:/etc/certs
    restart: on-failure

  # Configuration for the single-user servers
  jupyterlab:
    image: jupyter/scipy-notebook
    command: echo
    container_name: jupyterlab-science
    network_mode: none

volumes:
  jupyterhub_data: